### ISSUE TITLE
Resolve warnings produced by tensorflow when loading RNN

### ISSUE THREAD

**Issue by marksverdhei** [LBlend/mann-eller-kvinne#13]
A bunch of warnings occur when loading the keras model. Not sure why, but it should either be resolved or suppressed

**Comment by marksverdhei** [comment]
Temporary solution: 
suppress the excessive warnings produced by tensorflow, as I'm pretty sure they do not have any actual impact on our model.
Might train a new model with more epochs or parameters after we've gotten a validation framework down. Hopefully, it will not produce these warnings. The solution forces us to make an exception regarding pep8, as addressed in [tensorflow issue #31870](https://github.com/tensorflow/tensorflow/issues/31870#issuecomment-524705466). We have to set the environment variable before importing keras

**Comment by LBlend** [comment]
LGTM! I'll still keep the issue open though until you find a proper solution or decide to close the issue yourself
