### ISSUE TITLE
Site crashes on load when using Safari on iOS

### ISSUE THREAD

**Issue by LBlend** [LBlend/mann-eller-kvinne#3]
![image](https://user-images.githubusercontent.com/24893890/103041609-2a6ad000-4577-11eb-9654-092d96918ad5.png)

See https://github.com/vercel/next.js/issues/8347 for a potential solution

**Comment by marksverdhei** [comment]
The server should host the app with `npm serve` after calling `npm build` (instead of using `npm start`). 
It might prohibit the site from breaking (which is better), so we should try to reproduce it after doing this

**Comment by LBlend** [comment]
I will check whether or not this resolves the issue when I can get a hand on an iOS device. Probably within 2020.01.22.

I'll report back then

**Comment by LBlend** [comment]
> The server should host the app with `serve -s build` after calling `npm run-script build` (instead of using `npm start`).
> It might prohibit the site from breaking (which is better), so we should try to reproduce it after doing this
> Make sure to `npm install -g serve` first

I will check whether or not this resolves the issue when I can get a hand on an iOS device. Probably within 2020.01.22.

I'll report back to you then.

**Comment by LBlend** [comment]
> > The server should host the app with `serve -s build` after calling `npm run-script build` (instead of using `npm start`).
> > It might prohibit the site from breaking (which is better), so we should try to reproduce it after doing this
> > Make sure to `npm install -g serve` first
> 
> I will check whether or not this resolves the issue when I can get a hand on an iOS device. Probably by 2020-01-22.
> 
> I'll report back to you then.

Ok so I've tested the website and the error doesn't occur when the website is built. We should still consider fixing the issue though.

Even though I'm not 100% confident in what the issue is casued by, it is probably caused by [this](https://github.com/vercel/next.js/issues/8347#issuecomment-520857811). If this is the issue I suggest we fix it by doing the following:

* Delay sending of text to the API until the user has stopped typing anything
* Prevent text being sent to the API when the textbox is blank

By implementing the idea that I have proposed in the first bullet point, you can address the 2nd point at the same time. I actually implemented this feature in early builds of this project but decided to get rid of it before the initial commit due to complications.

**Comment by LBlend** [comment]
Since we're doing a rewrite, this won't be an issue anymore.
