### ISSUE TITLE
API won't run due to Tensorflow error - NotImplementedEror: Cannot convert a symbolic Tensor to a numpy array.

### ISSUE THREAD

**Issue by LBlend** [LBlend/mann-eller-kvinne#33]
## What is wrong?
When trying to run the API, Tensorflow raises a `NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported`

## System info
 - OS: Ubuntu 20.04, x86
 - Release: 2.1.0

**Comment by LBlend** [comment]
I have verified that this is a compatibility issue between packages and not a fault on our end. We should specify the version number for python packages in order to prevent this from happening in the future.

**Comment by LBlend** [comment]
Because of this, I have resorted to running the 1.0.0 release in production. I had to use a release without Tensorflwo

**Comment by marksverdhei** [comment]
Yep. I actually stumbled upon this problem in another problem as well. It's most likely caused by having a too recent version of numpy. I'd suggest making sure to install a tensorflow-compatible numpy version. I fixed it by installing numpy==1.19.5

**Comment by LBlend** [comment]
> Yep. I actually stumbled upon this problem in another project as well. It's most likely caused by having a too recent version of numpy. I'd suggest making sure to install a tensorflow-compatible numpy version. I fixed it by installing numpy==1.19.5

This resolves issue. Great! 👌

I will go ahead and push the changes
