### ISSUE TITLE
Replace all NLTK with scikit-learn

### ISSUE THREAD

**Issue by marksverdhei** [LBlend/mann-eller-kvinne#35]
NLTK is an old fashioned, awkward (imo). I think we should opt for a more modern classifier API. scikit learn is more modern and elegant. I think we should use this for the naive bayes (and possibly other) classifiers

**Comment by LBlend** [comment]
Having never used SciKit-learn, I can't attest to this. However I trust you on this and think we should go ahead with it in the rewrite
