### ISSUE TITLE
Make config setup for hyperparameter tuning of deep model

### ISSUE THREAD

**Issue by marksverdhei** [LBlend/mann-eller-kvinne#41]
We should use config files to manage hyperparameter tuning. Yaml is a pretty decent and readable format.
I'll be working on it as part of my mission to beat the bayes model.

**Comment by marksverdhei** [comment]
Is it time to merge this? Or was it blocked by something?

**Comment by LBlend** [comment]
> Is it time to merge this? Or was it blocked by something?

I haven't merged it because I stumbled upon an error when trying to run it myself.
https://github.com/LBlend/mann-eller-kvinne/pull/42#issuecomment-891891347
