### ISSUE TITLE
Move front end/backend into separate repos?

### ISSUE THREAD

**Issue by marksverdhei** [LBlend/mann-eller-kvinne#44]
Perhaps it's more clean given that the programs can be run independently.
Wdyt?

**Comment by LBlend** [comment]
I agree, though it will take some work. It'll be a task for the holidays when I've got the time for it.

I'm thinking of keeping the backend in this repo and moving the frontend to a separate one called "mann-eller-kvinne-frontend" or something among those lines.

**Comment by marksverdhei** [comment]
Would be pretty cool. At the moment, I'm fantasizing about replicating the API using some different technologies such as
* FastAPI
* sklearn for simple models
* pretrained embeddings for the neural model
* kubernetes with minikube for running training jobs
Of course, this can be done in a fork, or different repos
It might even be worth considering replacing the main thing with this, if it turns out better 😛

**Comment by LBlend** [comment]
Sounds good to me! I'm open to the idea of rewriting the backend i.e. using some if not all of the technologies you've mentioned. I find it hard to see the point of adding kubernetes support but other than that I agree.

**Comment by marksverdhei** [comment]
In this use case, it might not be necessary, but if we were to care about dynamic scalability and minimal downtime
it could be useful. Plus submitting / scheduling training jobs through kubernetes.
I think it could be nice, when showing this project to e.g. future employers that we really took the extra
steps (to give it the potential) to be scalable and robust as if it was for a business use case (which everything else is). 

Note that none of this has to be hosted by you. You can still do it the old fashioned way.
Most likely it will just be a folder with a couple yaml files that lets you plug your app/api right into any kubernetes cluster
Minikube requires at least 2 GB of memory and (I think) 20 gb of 

Wouldn't it be pretty neat to have kubernetes on your resume? 😎

**Comment by LBlend** [comment]
This calls for a rewrite of the frontend as well. It should be pretty easy to do and can be done in a couple of hours. I will get started on that in the near future

**Comment by LBlend** [comment]
I have now made a branch called "rewrite" in this repo and have started making some initial changes. I'll come back to you once the base structure of the rewrite is complete and (partially) working.
